facileImmobiliare:
    protocol: https
    host: facileimmobiliare.it
    port: '8081'
    basePath: /wp-json/wp/v2
    authorization: ''
    immobile:
      path: /immobile
    agente:
      path: /agente
              
application:
  autodiscovery: '18611155'
