facileImmobiliare:
    protocol: https
    host: facileimmobiliare.it
    port: '8081'
    basePath: /wp-json/wp/v2
    authorization: ''
    immobile:
      path: /immobile
    agente:
      path: /agente
      
wikiCasa:
    protocol: https
    host: sandbox.wikicasa.it
    port: '8081'
    basePath: /rest
    authorization: ''
    pathssoTokenForProvider: /auth/ssoTokenForProvider
    PublicKey: pubkey-FacileImmobiliare_provider
    PrivateKey: '![]'
    realEstateManagement:
      path: /realEstateWS
    agents:
      path: /agentWS
    agencies:
      path: /userWS

microsoftGraph:
  tokenUrl: login.microsoftonline.com
  graphUrl: graph.microsoft.com
  tenantID: 'a10eef83-cd5f-4430-93e7-c6b6a7551368'
  version: /v1.0
  users: /users
  calendar: /calendarview
  events: /events
  postCalendar: /calendar/events
  clientId: '8ed58fae-6274-4f6b-9951-543e6fb1cb77'
  clientSecret: '![fB+FYHKdFKd/tGGOoNAzCWprq/uZp0m9RhzOw5n/a32LPm87a360XcVoQPJCTTRz]'
  
realitycs:
  protocol: https
  host: webservice.realitycs.it
  token: /oauth/token
  authorization: '![]'
  grantType: grant_type
  username: ''
  password: '![]'
  tipologie: /tipologie
  poi: /poi
  smart: /smart
  smartAffitto: /smart/affitto
  
immobiliare:
    protocol: http
    host: feed.immobiliare.it
    port: '8081'
    basePath: /ws/import/immobiliare
    authorization: ''
    ximmosource: facileimmobiliarexc-ws
    immobile:
      path: /property
    agente:
      path: /company/realtor
    contentType: text/xml
              
application:
  autodiscovery: '18611155'
