facileImmobiliare:
    protocol: https
    host: staging.facileimmobiliare.it
    port: '8081'
    basePath: /wp-json/wp/v2
    authorization: ''
    immobile:
      path: /immobile
    agente:
      path: /agente

wikiCasa:
    protocol: https
    host: sandbox.wikicasa.it
    port: '8081'
    basePath: /rest
    authorization: ''
    pathssoTokenForProvider: /auth/ssoTokenForProvider
    PublicKey: pubkey-FacileImmobiliare_provider
    PrivateKey: '![X2cM1wzxG/ZEvsaLsq8NzBlSmDrya6mUIPPeJkPVil6VpubWrkBr/lNQoa0KyMiL/jVli3bB07ymZAY+9g6PhA0gwcUj1anzmpktOlO9zPE=]'
    realEstateManagement:
      path: /realEstateWS
    agents:
      path: /agentWS
    agencies:
      path: /userWS

microsoftGraph:
  tokenUrl: login.microsoftonline.com
  graphUrl: graph.microsoft.com
  tenantID: '41626452-eba2-41bc-be57-b41addba41e1'
  version: /v1.0
  users: /users
  calendar: /calendarview
  postCalendar: /calendar/events
    
application:
  autodiscovery: '18611144'
